package pack_eImport;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

public class B_Operation_Destination 
{
   public WebDriver driver;
   public String baseURL = "https://kulala.sk:Mercury015@pgitrade.pg.com/MercuryDev/Home.aspx";
	
	@Test(priority = 1)
  public void Verify_Login() 
  {
		System.setProperty("webdriver.chrome.driver","C:\\Program Files\\chromedriver.exe");
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		driver.get(baseURL);
		driver.navigate().refresh();
  }
	
	@Test(priority = 2)
	public void Operation_Destination_Approval() 
	{
		// Implicilty wait for 10 seconds
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);		
		// Upon login click on eImport tab at the top menu in the home page
		driver.findElement(By.xpath("//input[@id='MercuryHeader1_imgeImport']")).click();
		// Select a region - Asia
		driver.findElement(By.xpath("//a[@id='AAsia']")).click();
		// Select an Importing country - Vietnam
		driver.findElement(By.xpath("//input[@id='cmbCountry_I']")).click();
		driver.findElement(By.xpath("//td[text() = 'Vietnam']")).click();
		// Click on Submit button
		driver.findElement(By.xpath("//span[text() = 'Submit']")).click();
		// In the Dashboard, click on Request Number(that is created in the "A_Request_Creation" class
		// IMPORTANT NOTE : CHANGE THE REQUEST NUMBER ACCORDINGLY -- THE REQUEST NUMBER SHOULD BE THE SAME THAT IS GENERATED BY EXECUTONG THE CLASS "A_Request_Creation.java"
		driver.findElement(By.xpath("//span[text() = 'VN-18-000739']")).click();
		// Click on Edit in the "Request View" page
		driver.findElement(By.xpath("//span[@class = 'dx-vam' and text() = 'Edit']")).click();
		// Click on "Operations Destination" tab in the left menu
		driver.findElement(By.xpath("//a[text() = 'Operations Destination']")).click();
		// Click on Edit icon in the "Operations Destination" grid
		driver.findElement(By.xpath("//img[@id='ctl00_MainContent_gvOperationsDestination_cell0_7_ExcelItemEditImg']")).click();
		// Select " Importer of Record (IOR)" from "HTS Classification" layer
		driver.findElement(By.xpath("//input[@id='ctl00_MainContent_cmbImporterofRecord_I']")).click();
		driver.findElement(By.xpath("//td[@id='ctl00_MainContent_cmbImporterofRecord_DDD_L_LBI1T0']")).click();
		// Enter "DutyRate - Normal as per tariff" from "Description Of Goods Customs"
		driver.findElement(By.xpath("//input[@id='ctl00_MainContent_txtNormalDutyRate']")).sendKeys("Test Duty Rate");
		// Select "is FTA Applicable" as No from "Duty Rate" layer
		driver.findElement(By.xpath("//input[@id='ctl00_MainContent_rblIsFTAApplicable_RB1_I']")).click();
		// Enter Anti-dumping duty rate" from "Duty Rate"
		driver.findElement(By.xpath("//input[@id='ctl00_MainContent_txtAntiDumpingDutyRate']")).sendKeys("Test Anti-dumping duty rate");
		//select "Special Customs Regime" from "Duty Rate"
		driver.findElement(By.xpath("//input[@id='ctl00_MainContent_cmbSpecialCustomsRegime_I']")).click();
		driver.findElement(By.xpath("//td[@id='ctl00_MainContent_cmbSpecialCustomsRegime_DDD_L_LBI1T0']")).click();
		//select "Any Quota imposed of this product?" from "Duty Rate"
		driver.findElement(By.xpath("//input[@id='ctl00_MainContent_rblAnyQuotaimposed_RB1_I']")).click();
		//select "Import License / Permit / Certification?" from Duty Rate
		driver.findElement(By.xpath("//input[@id='ctl00_MainContent_rblSubjecttoImportLicence_RB1_I']")).click();
		//select"Import License / permit / Certification available now? "from "Duty Rate"
		driver.findElement(By.xpath("//input[@id='ctl00_MainContent_rblIsTheImportLicence_RB1_I']")).click();
		//select"Application for every shipment?" from "Duty Rate"
		driver.findElement(By.xpath("//input[@id='ctl00_MainContent_rblApplicationForEveryShipment_RB1_I']")).click();
		//Click on "Update" button in "Duty Rate"
		driver.findElement(By.xpath("//span[@class = 'dx-vam' and text() = 'Update']")).click();
		// Handle Alert
		Alert alert = driver.switchTo().alert();
		System.out.println(alert.getText());
		alert.accept();
		// CLick on Submit
		driver.findElement(By.xpath("//span[@class = 'dx-vam' and text() = 'Submit']")).click();
		Alert alert1 = driver.switchTo().alert();
		System.out.println(alert1.getText());
		alert1.accept();
		driver.close();
						
	}
}
