package pack_eImport;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

	public class D_Customs_Compliance_Origin 
	{
	public WebDriver driver;
	public String baseURL = "https://nemana.vk:Vertex14@pgitrade.pg.com/MercuryDev/Home.aspx";
	
	@Test(priority = 1)
  	public void Verify_Login() 
	{
	  	System.setProperty("webdriver.chrome.driver","C:\\Program Files\\chromedriver.exe");
	 	driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		driver.get(baseURL);
		driver.navigate().refresh();
	}
	
	@Test(priority = 2)
	public void Customs_Compliance_Origin()
	{
		// Implicilty wait for 10 seconds
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);		
		// Upon login click on eImport tab at the top menu in the home page
		driver.findElement(By.xpath("//input[@id='MercuryHeader1_imgeImport']")).click();
		// Select a region - Asia
		driver.findElement(By.xpath("//a[@id='AAsia']")).click();
		// Select an Importing country - Vietnam
		driver.findElement(By.xpath("//input[@id='cmbCountry_I']")).click();
		driver.findElement(By.xpath("//td[text() = 'Vietnam']")).click();
		// Click on Submit button
		driver.findElement(By.xpath("//span[text() = 'Submit']")).click();
		// In the Dashboard, click on Request Number(that is created in the "A_Request_Creation" class
		// IMPORTANT NOTE : CHANGE THE REQUEST NUMBER ACCORDINGLY -- THE REQUEST NUMBER SHOULD BE THE SAME THAT IS GENERATED BY EXECUTONG THE CLASS "A_Request_Creation.java"
		driver.findElement(By.xpath("//span[text() = 'VN-18-000739']")).click();
		// Click on Edit button in the "Request View" page
		driver.findElement(By.xpath("//span[@class = 'dx-vam' and text() = 'Edit']")).click();
		// Click on "Edit" icon in the "Customs Compliance Destination" layer
		driver.findElement(By.xpath("//img[@id='ctl00_MainContent_gvCustomsComplianceOrigin_cell0_7_ExcelItemEditImg']")).click();
		// Click on "Yes" radio button 
		driver.findElement(By.xpath("//input[@id='ctl00_MainContent_rblIsProductFtaBenefits_RB1_I']")).click();
		// Click on Update button
		driver.findElement(By.xpath("//span[@class = 'dx-vam' and text() = 'Update']")).click();
		// Handle ALert
		Alert alert = driver.switchTo().alert();
		System.out.println(alert.getText());
		alert.accept();
		// CLick on Submit button
		driver.findElement(By.xpath("//span[@class = 'dx-vam' and text() = 'Submit']")).click();
		// Handle ALert
		Alert alert1 = driver.switchTo().alert();
		System.out.println(alert1.getText());
		alert1.accept();
		driver.close();
	}
	
}
	
	
	
	
